/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbsoluteContainer: typeof import('./src/components/AbsoluteContainer/index.vue')['default']
    Auth: typeof import('./src/components/Auth/index.vue')['default']
    AuthAll: typeof import('./src/components/AuthAll/index.vue')['default']
    BatchActionBar: typeof import('./src/components/BatchActionBar/index.vue')['default']
    CascaderArea: typeof import('./src/components/CascaderArea/index.vue')['default']
    Copyright: typeof import('./src/components/Copyright/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    FixedActionBar: typeof import('./src/components/FixedActionBar/index.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./src/components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    PageMain: typeof import('./src/components/PageMain/index.vue')['default']
    Result: typeof import('./src/components/Result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Trend: typeof import('./src/components/Trend/index.vue')['default']
  }
}
